// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package resource is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	RequestModule
	ResponseModule
*/
package resource

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestModule struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Body string `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
}

func (m *RequestModule) Reset()                    { *m = RequestModule{} }
func (m *RequestModule) String() string            { return proto.CompactTextString(m) }
func (*RequestModule) ProtoMessage()               {}
func (*RequestModule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RequestModule) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *RequestModule) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type ResponseModule struct {
	Type   string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Data   string `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	Status int32  `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,4,opt,name=msg" json:"msg,omitempty"`
}

func (m *ResponseModule) Reset()                    { *m = ResponseModule{} }
func (m *ResponseModule) String() string            { return proto.CompactTextString(m) }
func (*ResponseModule) ProtoMessage()               {}
func (*ResponseModule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResponseModule) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ResponseModule) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *ResponseModule) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ResponseModule) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestModule)(nil), "resource.RequestModule")
	proto.RegisterType((*ResponseModule)(nil), "resource.ResponseModule")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x28, 0x4a, 0x2d, 0xce, 0x2f,
	0x2d, 0x4a, 0x4e, 0x55, 0x32, 0xe7, 0xe2, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xf1, 0xcd,
	0x4f, 0x29, 0xcd, 0x49, 0x15, 0x12, 0xe2, 0x62, 0x29, 0xa9, 0x2c, 0x48, 0x95, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x41, 0x62, 0x49, 0xf9, 0x29, 0x95, 0x12, 0x4c, 0x10, 0x31, 0x10,
	0x5b, 0x29, 0x89, 0x8b, 0x2f, 0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x15, 0xbf, 0xce, 0x94,
	0xc4, 0x92, 0x44, 0x98, 0x4e, 0x10, 0x5b, 0x48, 0x8c, 0x8b, 0xad, 0xb8, 0x24, 0xb1, 0xa4, 0xb4,
	0x58, 0x82, 0x59, 0x81, 0x51, 0x83, 0x35, 0x08, 0xca, 0x13, 0x12, 0xe0, 0x62, 0xce, 0x2d, 0x4e,
	0x97, 0x60, 0x01, 0x2b, 0x05, 0x31, 0x93, 0xd8, 0xc0, 0xae, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xfd, 0x02, 0xb6, 0xfe, 0xbe, 0x00, 0x00, 0x00,
}
